@startuml foco

Class Usuario

Class Foco{
- EstadoFoco estado
+ Encender ()
+ Apagar()
+Leerestado() : EstadoFoco
}

class EstadoFoco
class SerieFocos
    - Foco focos [10]
    +MostrarFocos()
    +EncenderFocos()
    +ApagarFocos()
}

usuario o-- Foco
Foco*-- Estado Foco
EstadoFoco --|> Texto 
SerieFocos "1" *-- "10" Foco
Usuario o-- SerieFocos

@enduml